// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Permission struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	CreatedAt sql.NullTime
}

type UserRole struct {
	UserID int32
	RoleID int32
}
